/**
 * Unit Tests — userController.js
 * Generated by: Unit Test Generator Agent
 * Bug: API-404 — GET /api/users/:id returns 404 for valid user IDs
 * Skill: unit-tests-FIRST.md
 *
 * Tests cover ONLY the changed code: getUserById (the parseInt fix).
 * getAllUsers is unchanged and is not re-tested here.
 */

const httpMocks = require('node-mocks-http');
const { getUserById } = require('../src/controllers/userController');

// ---------------------------------------------------------------------------
// Helper — build mock req/res pair (Fast: no real HTTP, Independent: fresh per test)
// ---------------------------------------------------------------------------
function buildMocks(params = {}) {
  const req = httpMocks.createRequest({ params });
  const res = httpMocks.createResponse();
  return { req, res };
}

// ---------------------------------------------------------------------------
// getUserById — Happy Path
// ---------------------------------------------------------------------------
describe('getUserById — happy path', () => {
  test('should return user with status 200 for a valid numeric ID (string param "123")', async () => {
    // Arrange
    const { req, res } = buildMocks({ id: '123' });

    // Act
    await getUserById(req, res);

    // Assert
    expect(res.statusCode).toBe(200);
    const data = res._getJSONData();
    expect(data).toEqual({ id: 123, name: 'Alice Smith', email: 'alice@example.com' });
  });

  test('should return user with status 200 for ID "456"', async () => {
    const { req, res } = buildMocks({ id: '456' });
    await getUserById(req, res);
    expect(res.statusCode).toBe(200);
    const data = res._getJSONData();
    expect(data).toEqual({ id: 456, name: 'Bob Johnson', email: 'bob@example.com' });
  });

  test('should return user with status 200 for ID "789"', async () => {
    const { req, res } = buildMocks({ id: '789' });
    await getUserById(req, res);
    expect(res.statusCode).toBe(200);
    const data = res._getJSONData();
    expect(data).toEqual({ id: 789, name: 'Charlie Brown', email: 'charlie@example.com' });
  });
});

// ---------------------------------------------------------------------------
// getUserById — Error Path (404)
// ---------------------------------------------------------------------------
describe('getUserById — not found', () => {
  test('should return 404 when user ID does not exist', async () => {
    const { req, res } = buildMocks({ id: '999' });
    await getUserById(req, res);
    expect(res.statusCode).toBe(404);
    const data = res._getJSONData();
    expect(data).toEqual({ error: 'User not found' });
  });

  test('should return 404 for ID "0" (not in array)', async () => {
    const { req, res } = buildMocks({ id: '0' });
    await getUserById(req, res);
    expect(res.statusCode).toBe(404);
    expect(res._getJSONData()).toEqual({ error: 'User not found' });
  });
});

// ---------------------------------------------------------------------------
// getUserById — Edge Cases (regression for the original bug)
// ---------------------------------------------------------------------------
describe('getUserById — type coercion regression (the original bug)', () => {
  test('should NOT return 404 when ID is passed as string "123" (was the bug)', async () => {
    // Before the fix: users.find(u => u.id === "123") always returned undefined
    // After the fix: parseInt("123", 10) === 123 → user found
    const { req, res } = buildMocks({ id: '123' });
    await getUserById(req, res);
    // If this returns 404, the bug is back
    expect(res.statusCode).not.toBe(404);
    expect(res._getJSONData().id).toBe(123);
  });

  test('should handle ID with extra whitespace trimmed by parseInt', async () => {
    // parseInt(" 123 ", 10) returns 123 — defensive edge case
    const { req, res } = buildMocks({ id: ' 123 ' });
    await getUserById(req, res);
    // parseInt handles leading spaces; this is acceptable behavior
    expect(res.statusCode).toBe(200);
  });
});
